/**
 * Tiny, safe Markdown renderer for chat bubbles.
 * Supports: **bold**, *italic*, `inline code`, [link](url),
 * unordered lists (- or *), ordered lists (1.), paragraphs,
 * and `### h3` / `## h2` headings. NO raw HTML pass-through.
 *
 * Output: an array of { type, ... } blocks for the Vue template to render.
 * All HTML is generated by us, never from user input.
 */

const escapeHtml = (s) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')

/* Escape everything, then bring back our tiny markdown syntax. */
function inline(text) {
  let out = escapeHtml(text)

  /* inline code first so we don't process markdown inside it */
  out = out.replace(/`([^`]+)`/g, (_, c) => `<code>${c}</code>`)

  /* links: [label](https://url) — only http(s) and mailto */
  out = out.replace(
    /\[([^\]]+)\]\(((?:https?:\/\/|mailto:)[^\s)]+)\)/g,
    (_, label, href) => {
      const safe = String(href).replace(/"/g, '&quot;')
      return `<a href="${safe}" target="_blank" rel="noopener noreferrer">${label}</a>`
    }
  )

  /* bold then italic — order matters */
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  out = out.replace(/(^|[^*])\*([^*\n]+)\*(?!\*)/g, '$1<em>$2</em>')

  return out
}

/**
 * Render a markdown string into a list of block descriptors.
 * @param {string} src
 * @returns {Array<{type:string, html?:string, level?:number, items?:string[]}>}
 */
export function renderMarkdown(src) {
  const blocks = []
  if (!src) return blocks

  const lines = String(src).replace(/\r\n/g, '\n').split('\n')
  let i = 0
  while (i < lines.length) {
    const line = lines[i]

    /* blank line → skip */
    if (!line.trim()) { i++; continue }

    /* heading */
    const h = line.match(/^(#{1,4})\s+(.+)$/)
    if (h) {
      blocks.push({ type: 'heading', level: h[1].length, html: inline(h[2].trim()) })
      i++
      continue
    }

    /* unordered list — gather contiguous '- ' or '* ' lines */
    if (/^\s*[-*]\s+/.test(line)) {
      const items = []
      while (i < lines.length && /^\s*[-*]\s+/.test(lines[i])) {
        items.push(inline(lines[i].replace(/^\s*[-*]\s+/, '')))
        i++
      }
      blocks.push({ type: 'ul', items })
      continue
    }

    /* ordered list */
    if (/^\s*\d+\.\s+/.test(line)) {
      const items = []
      while (i < lines.length && /^\s*\d+\.\s+/.test(lines[i])) {
        items.push(inline(lines[i].replace(/^\s*\d+\.\s+/, '')))
        i++
      }
      blocks.push({ type: 'ol', items })
      continue
    }

    /* paragraph — gather contiguous non-blank, non-special lines */
    const paraLines = []
    while (
      i < lines.length &&
      lines[i].trim() &&
      !/^#{1,4}\s+/.test(lines[i]) &&
      !/^\s*[-*]\s+/.test(lines[i]) &&
      !/^\s*\d+\.\s+/.test(lines[i])
    ) {
      paraLines.push(lines[i])
      i++
    }
    if (paraLines.length) {
      blocks.push({ type: 'p', html: inline(paraLines.join(' ')) })
    }
  }
  return blocks
}